export enum SocketResponses {
  ERROR_RESPONSE = 'ERROR_RESPONSE',
  PLAYER_FIRE_RESPONSE = 'PLAYER_FIRE_RESPONSE',
  CHAT_FIRE_RESPONSE = 'CHAT_FIRE_RESPONSE',
  START_RESPONSE = 'START_RESPONSE',
  VOTES_RESPONSE = 'VOTES_RESPONSE',
  WINNER_RESPONSE = 'WINNER_RESPONSE',
  CONNECTED = 'connect',
  DISCONNECTED = 'disconnect'
}

export enum SocketEmitters {
  START = 'START',
  VOTES = 'VOTES',
  FIRE = 'PLAYER_FIRE'
}
